### ISSUE TITLE
IllegalAccessError DynamoDBProxyServer tried to access protected method AbstractContainer in Jetty

### ISSUE THREAD

**Issue by thomasturrell** [awslabs/amazon-dynamodb-local-samples#10]
### Describe the bug

In Spring Boot 3.2.0 the managed version of Jetty Server is 12.0.3. DynamoDB Local uses Jetty Server version 11.0.17.

Currently DynamoDB Local cannot be used in a Spring Boot 3.2.0 application without workarounds.

### Expected Behaviour

DynamoDB Local should work with the latest version of Jetty Server (12.0.3 at time of writing).

### Current Behaviour

```
2023-11-28T17:11:28.4697837Z Caused by: java.lang.IllegalAccessError: class com.amazonaws.services.dynamodbv2.local.server.DynamoDBProxyServer tried to access protected method 'void org.eclipse.jetty.server.Handler$AbstractContainer.<init>()' (com.amazonaws.services.dynamodbv2.local.server.DynamoDBProxyServer and org.eclipse.jetty.server.Handler$AbstractContainer are in unnamed module of loader 'app')
2023-11-28T17:11:28.4701618Z 	at com.amazonaws.services.dynamodbv2.local.server.DynamoDBProxyServer.setUpHandler(DynamoDBProxyServer.java:52)
2023-11-28T17:11:28.4703363Z 	at com.amazonaws.services.dynamodbv2.local.server.DynamoDBProxyServer.<init>(DynamoDBProxyServer.java:39)
2023-11-28T17:11:28.4704957Z 	at com.amazonaws.services.dynamodbv2.local.main.ServerRunner.createServer(ServerRunner.java:149)
2023-11-28T17:11:28.4706719Z 	at com.amazonaws.services.dynamodbv2.local.main.ServerRunner.createServerFromCommandLineArgs(ServerRunner.java:134)
```

**Comment by thomasturrell** [comment]
@shetsa-amzn Can you help me direct this bug report to the correct team?

**Comment by thomasturrell** [comment]
@gorelov1 Can you help me direct this bug report to the correct team?

**Comment by shetsa-amzn** [comment]
We appreciate your feedback and we are currently reviewing this. We will update as soon as we have more information about next steps.

**Comment by shetsa-amzn** [comment]
Hi, we currently have this planned in our issues backlog. We do not have an ETA, but it is being prioritized. We will provide a status update once this is in progress.

**Comment by shetsa-amzn** [comment]
Hello @thomasturrell ,

The DynamoDB DevEx team is continuously making improvements to DynamoDB local. As we have received feedback from you as a user of DynamoDB local as a Maven dependency. Our latest improvement to DynamoDB local is an upgrade to Jetty 12 to be compatible with Spring Boot 3.2.0. We are reaching out to you to see if you would like to participate in the early testing of our DynamoDB local beta version, which includes this upgrade. We would really appreciate your support as your participation will help us ensure high quality user experience with this upgrade before we launch to the general public.

If you would like to participate in early testing of our DynamoDB local beta release, please send us an email at: [aws-ddblocal-feedback@amazon.com](mailto:aws-ddblocal-feedback@amazon.com).

Regards,
The DynamoDB DevEx Team

**Comment by shetsa-amzn** [comment]
Today, we are excited to announce that DynamoDB local for [Amazon DynamoDB](https://aws.amazon.com/dynamodb/) upgrades to Jetty 12 and JDK 17. We recommend that you run the latest version (2.3.0) of DynamoDB local to utilize the most recent updates and features of DynamoDB local for your development and testing use cases.

https://aws.amazon.com/about-aws/whats-new/2024/03/amazon-dynamodb-local-upgrades-jetty-12-jdk-17/
