### ISSUE TITLE
DynamoDBLocal jar incorrectly includes Kotlin classes and other dependencies when packaged for use in Maven

### ISSUE THREAD

**Issue by rnewman** [awslabs/amazon-dynamodb-local-samples#15]
I have a fairly straightforward Spring Boot application that uses `aws.sdk.kotlin:dynamodb:1.1.2`. I was attempting to use DynamoDBLocal for testing.

Adding the following:

```
    testRuntimeOnly("com.amazonaws:DynamoDBLocal:2.3.0")
```

to my `build.gradle.kts` causes DynamoDB *client* operations to fail at runtime:

```
java.lang.IncompatibleClassChangeError: Found class kotlin.time.TimeMark, but interface was expected
	at aws.smithy.kotlin.runtime.http.interceptors.OperationTelemetryInterceptor.readAfterExecution(OperationTelemetryInterceptor.kt:58)
	at aws.smithy.kotlin.runtime.http.interceptors.InterceptorExecutor.readAfterExecution-bjn95JY(InterceptorExecutor.kt:318)
	at aws.smithy.kotlin.runtime.http.operation.OperationHandler.call(SdkOperationExecution.kt:214)
```

This is because `DynamoDBLocal-2.3.0.jar` bundles all of its dependencies, **including the Kotlin runtime**. That is probably correct for an "uberjar" that you can run, but it is not correct for a Maven dependency that will be built with e.g., Gradle.

If I delete `kotlin/time` from the jar, the runtime error shifts, as expected:

```
java.lang.NoSuchMethodError: 'java.lang.Comparable kotlin.collections.CollectionsKt.minOrThrow(java.lang.Iterable)'
	at aws.smithy.kotlin.runtime.auth.awscredentials.CachedCredentialsProvider$resolve$3.invokeSuspend(CachedCredentialsProvider.kt:64)
```

If I delete `^kotlin/` from the jar, runtime errors disappear, and DDBL seems to start correctly:

```
Initializing DynamoDB Local with the following configuration:
Port:	59828
InMemory:	true
Version:	2.3.0
DbPath:	null
SharedDb:	false
shouldDelayTransientStatuses:	false
CorsParams:	null
```

**Suggestion**: the standalone jar you build for command-line use and the jar you build for use in a dependency management system should be different. Please do not include your dependencies in the jar.

**Comment by shetsa-amzn** [comment]
We appreciate your feedback and we are currently reviewing this. We will update as soon as we have more information about next steps.

**Comment by furstenheim-goodnotes** [comment]
Similar error here. Got `TestCoroutineScheduler$timeSource cannot be cast to class kotlin.time.TimeSource$WithComparableMarks` just by doing `UnconfinedTestDispatcher()` because the kotlin.time is overridden by dynamodb local.

I just couldn't use the library.

**Comment by jpbelang** [comment]
This issue is somewhere around four years old.  It was originally reported back in 2021.
Will it ever be fixed ?

**Comment by Cililing** [comment]
@jpbelang not only reported back in 2021, but some people give the solution already (publishing two jars), but were jumped over different repositories and contact teams for months/years. AWS team looks like they just don't care - no one will drop AWS stack because of this.

AWS, you are getting 🧇 for being one of the worst support and maintainers ever.

**Comment by ragboyjr** [comment]
I created a gradle convention plugin to download ddb local and automatically patch it and include it in the testImplementation dependencies.

```kotlin
// in buildSrc/src/main/kotlin/dynamodb-local.java-conventions.gradle.kts
import org.gradle.kotlin.dsl.creating
import org.gradle.kotlin.dsl.getValue
import org.gradle.kotlin.dsl.kotlin
import org.gradle.kotlin.dsl.support.zipTo

plugins {
    kotlin("jvm")
}

val dynamodbLocal by configurations.creating

dependencies {
    dynamodbLocal("com.amazonaws:DynamoDBLocal:2.6.0")
    testImplementation(
        files(
            dynamodbLocal.files.map {
                it.takeUnless { it.name.startsWith("DynamoDBLocal") } ?: file("build/patched-libs/DynamoDBLocal.jar")
            },
        ),
    )
}

// Unfortunately, DynamoDBLocal 2.6.0 includes the kotlin stdlib at 1.6.*, we need to patch the jar
// to remove the kotlin stdlib so everything can work
// https://github.com/awslabs/amazon-dynamodb-local-samples/issues/15
tasks.register("patchDynamoDBLocalJar") {
    val dynamoDBLocalJar = dynamodbLocal.files.find {
        it.name.startsWith("DynamoDBLocal") && it.extension == "jar"
    } ?: error("DynamoDB Jar not Found")

    val patchedJar = layout.buildDirectory.file("patched-libs/DynamoDBLocal.jar")

    inputs.file(dynamoDBLocalJar)
    outputs.file(patchedJar)

    doLast {
        val tempDir = layout.buildDirectory
            .dir("tmp/patch-dynamodb-local")
            .get()
            .asFile
        tempDir.deleteRecursively()
        tempDir.mkdirs()

        // Unpack the JAR
        copy {
            from(zipTree(dynamoDBLocalJar))
            into(tempDir)
            exclude("kotlin/**") // Exclude the offending folder
        }

        zipTo(patchedJar.get().asFile, tempDir)
    }
}

tasks.matching { it.name in listOf("compileTestKotlin", "compileIntegrationTestKotlin") }.configureEach {
    dependsOn("patchDynamoDBLocalJar")
}
```

I can then leverage this in any of my gradle subprojects with:

```kotlin
plugins {
  id("dynamodb-local.java-conventions")
}
```

**Comment by yonigibbs** [comment]
If using the workaround above from @ragboyjr (which I did: thanks for that!), one thing to be aware of is that it turns every child dependency of `DynamoDBLocal` into a local `file` dependency. This means that Gradle doesn't know what version it is, which can confuse its version resolution algorithm. This means that if you explicitly depend on a newer version of one of the dependencies of `DynamoDBLocal` (e.g. Mockito), the older version might incorrectly be chosen.

One way around this is to slightly alter the Gradle task above to do this instead:
```kotlin
dependencies {
    // Create a temporary configuration with just DynamoDBLocal as a dep
    dynamodbLocal("com.amazonaws:DynamoDBLocal:2.6.0")

    // Loop round all the transitive deps that this added, and add them as transitive deps to the current module
    dynamodbLocal.resolvedConfiguration.firstLevelModuleDependencies.single().children.forEach { resolvedDep ->
        testImplementation(
            with(resolvedDep) {
                "$moduleGroup:$moduleName:$moduleVersion"
            }
        )
    }

    // Add the custom JAR built by the `patchDynamoDBLocalJar` below.
    testImplementation(
        files(file("build/patched-libs/DynamoDBLocal.jar"))
    )
}
```

**Comment by danielsanchezsa** [comment]
Hi all.
Thank you for the feedback and for sharing the workaround solution. 
We acknowledge this issue. We are reviewing the next steps on this. We will keep this thread updated as soon as we have more information.

**Comment by jsyrjala** [comment]
This same issue is still with version DynamoDBLocal 3.0.0

Bunch of classes from some old kotlin version are included in. If you use DynamoDBLocal as maven dependency, these will conflict with the version of kotlin you are using.

Including this jar as dependency will make this kind of valid kotlin 2.2 code to fail

```
val percentages: List<Double> = listOf(1.0, 2.0)
val m =  percentages.max()

=> 

java.lang.NoSuchMethodError: 'double kotlin.collections.CollectionsKt.maxOrThrow(java.lang.Iterable)'
```
This is because whatever old kotlin version is included in the .jar doesn't have maxOrThrow method.


```
jar -tf /tmp/DynamoDBLocal-3.0.0.jar|grep kotlin|grep .class
com/amazon/ion/shaded_/do_not_use/kotlin/_Assertions.class
com/amazon/ion/shaded_/do_not_use/kotlin/jvm/functions/Function1.class
com/amazon/ion/shaded_/do_not_use/kotlin/jvm/internal/Intrinsics.class
kotlin/ArrayIntrinsicsKt.class
kotlin/BuilderInference.class
kotlin/CharCodeJVMKt.class
kotlin/CharCodeKt.class
kotlin/CompareToKt.class
kotlin/ContextFunctionTypeParams.class
kotlin/DeepRecursiveFunction.class
kotlin/DeepRecursiveKt.class
kotlin/DeepRecursiveScope.class
kotlin/DeepRecursiveScopeImpl$crossFunctionCompletion$$inlined$Continuation$1.class
kotlin/DeepRecursiveScopeImpl.class
kotlin/Deprecated.class
kotlin/DeprecatedSinceKotlin.class
kotlin/DeprecationLevel.class
kotlin/DslMarker.class
kotlin/ExceptionsKt.class
kotlin/ExceptionsKt__ExceptionsKt.class
kotlin/Experimental$Level.class
kotlin/Experimental.class
kotlin/ExperimentalMultiplatform.class
kotlin/ExperimentalStdlibApi.class
kotlin/ExperimentalUnsignedTypes.class
kotlin/ExtensionFunctionType.class
kotlin/Function.class
kotlin/HashCodeKt.class
kotlin/InitializedLazyImpl.class
kotlin/KotlinNothingValueException.class
kotlin/KotlinNullPointerException.class
kotlin/KotlinVersion$Companion.class
kotlin/KotlinVersion.class
kotlin/KotlinVersionCurrentValue.class
kotlin/LateinitKt.class
kotlin/Lazy.class
kotlin/LazyKt.class
kotlin/LazyKt__LazyJVMKt$WhenMappings.class
kotlin/LazyKt__LazyJVMKt.class
kotlin/LazyKt__LazyKt.class
kotlin/LazyThreadSafetyMode.class
kotlin/Metadata$DefaultImpls.class
kotlin/Metadata.class
kotlin/NoWhenBranchMatchedException.class
kotlin/NotImplementedError.class
kotlin/NumbersKt.class
kotlin/NumbersKt__BigDecimalsKt.class
kotlin/NumbersKt__BigIntegersKt.class
kotlin/NumbersKt__FloorDivModKt.class
kotlin/NumbersKt__NumbersJVMKt.class
and so on...
```

**Comment by anshalantony10** [comment]
Hi all, 
We were able to create a distribution that can possibly solve the kotlin dependency conflicts by not packaging kotlin classes in the jar
 
If anyone is willing to test it out before release please reply on this thread. 

Thanks!

**Comment by ragboyjr** [comment]
Yes! I’d love to test it out!

**Comment by ragboyjr** [comment]
@anshalantony10 what do I need to do start testing?

**Comment by dataGeeek** [comment]
I would also be interested

**Comment by anshalantony10** [comment]
Hi Folks, 
Apologies but due to some technical limitations it was not possible to enable external testing but we have carried out extensive testing. You can expect the changes to be available in the upcoming release of DDBLocal. 

Would appreciate it if you'll can test it out then and update on this thread.

**Comment by anshalantony10** [comment]
The new version 3.2.0 is out now and available through Maven. Could someone please test it and update here?

Thanks!

**Comment by ragboyjr** [comment]
Amazing! It works now! 

I was able to test on my project that was consistently failing on DDB Local 3.1.0 and upgrading to 3.2.0 fixed the errors! I also double checked that ddb local was being loaded before kotlin-stdlib in my classpath and everything works great! thank you all so much!

**Comment by anshalantony10** [comment]
Hey Folks, 

As per my understanding adding kotlin-stdlib-1.5.32.jar to the pom.xml of DynamoDBLocal should not conflict with the kotlin version in your project. Since the  conflict was coming from the kotlin jars being included inside the DDBLocal Jar - Which is not the case anymore.  

Is this correct or would adding these still cause runtime dependency conflicts?


Context: [issue](https://github.com/awslabs/amazon-dynamodb-local-samples/issues/35)
Since it is a not an optimal experience to specify other dependencies to use PartiQL APIs with DynamoDBLocal it would be ideal to have them included in the pom.xml

**Comment by ragboyjr** [comment]
ya, having them in the pom should be totally fine, the problem is that kotlin 1.5.2 was being explicitly included in the classpath even if you were depending on a later version of kotlin. Having this in the pom should enable our dependency managers (maven/gradle) to use the latest version between all of the dependencies.

Kotlin 1.5.2 is pretty old tho :D, so there could definitely be some value in upgrading this to 1.9.x at a minimum but ideally a 2.x

**Comment by anshalantony10** [comment]
I will be closing this Thread since this issue is fixed in all versions post 3.2.0 and the linked issue is also fixed in 3.3.1
Thanks Folks
